#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""A function to generate a fibonacci sequence"""


def fibonacci(maxint):
    """Integer to be used as upper bound.

    Args:
        maxint(int): The upper bound for the while loop.

    Returns:
        A list of sequence of numbers generated by looped arithmetic.
    Examples:
        >>> fibonacci(10)
        [0, 1, 1, 2, 3, 5, 8]

    """
    int1, int2 = 0, 1
    fiblist = [int1, ]
    while int2 < maxint:
        fiblist.append(int2)
        int1, int2 = int2, int1 + int2
    return fiblist
